---
title: "Programowanie strukturalne - Kolokwium 2 - Zestaw 323"
lang: pl
output:
  pdf_document: default
---

**Każde zadanie powinno być w oddzielnym pliku. Rozwiązanie jako archiwum zip umieść na
swoim indywidualnym prywatnym kanale MS Teams pod poleceniem.** 

1. W folderze Debug323 znajduje się projekt z kodem w języku C.
W pliku main.c w niektórych linijkach są komentarze.
Twoim zadaniem jest wpisanie wartości odpowiednich zmiennych po wykonaniu konkretnej linii kodu.
Dopisywanie nowych instrukcji jest zabronione.

*Punktacja: 7 pkt.*

2. Napisz funkcję, której argumentem jest napis. Funkcja ma w napisie ustawić znak zerowy na miejscu po ostatniej samogłosce w tym napisie. Jeśli napis nie ma samogłosek, funkcja ma nie robić nic. Stwórz przypadek testowy.

Przykład: "Olsztyn" ma być zamieniony na "Olszty". 

*Punktacja: 9 pkt.*

3. Napisz funkcję, której argumentem jest dwuwymiarowa tablica tablic (zawierająca zmienne typu `int`) oraz jej wymiary $n$ i $m$. Funkcja ma odwrócić kolejność elementów w wierszach o parzystych indeksach. Stwórz przypadek testowy.

Przykład.

$$\left[\begin{array}{ccc} 2 & 3 & -3\\ 1 & 4 & 7 \\ -3 & -6 & 11 \\ -2 & 8 & 23\end{array}\right] \longrightarrow\left[\begin{array}{ccc} -3 & 3 & 2\\ 1 & 4 & 7 \\ 11 & -6 & -3 \\ -2 & 8 & 23\end{array}\right]$$

*Punktacja: 9 pkt.*

4. Stwórz strukturę `Biegacz` o dwóch polach `imie` (napis) oraz `rekord` (`dowolny typ całkowity`). Następnie stwórz funkcję, której argumentami jest tablica struktur `Biegacz` oraz rozmiar tablicy. Funkcja ma zwrócić rekord biegacza z najlepszym (najmniejszym liczbowo) wynikiem (w przypadku kilku równych wyników, ma zwrócić wynik ostatniego). Stwórz przypadek testowy.

*Punktacja: 11 pkt.*

5. Napisz funkcję, która przyjmuje jako argument dwie listy bez głowy o elementach typu:

```c
struct node {
    int x;
    struct node * next;
};
```

Funkcja zwraca 1 jeśli obie listy są mają po tyle samo elementów ujemnych oraz 0 w przeciwnym wypadku. Stwórz przypadek testowy.

*Punktacja: 14 pkt.*
